### ISSUE TITLE
Curious on expansion on this

### ISSUE THREAD

**Issue by demariners** [Fragtality/PilotsDeck_FNX#4]
I gotta be honest.  This is some AMAZING work you are doing here.  I am curious though how you found the patterns to extract this information.  I am wondering if we can extract even more information and add them somehow.  I know, in my case, I have an OVHD panel that has the ADIRS LEDs.  That is not exposed but would be Nice to add to realism.  Is there a hint or something you can provide that shows how you found these patterns and so forth?

**Comment by Fragtality** [comment]
You could also write me a PM on the various platforms instead of opening an issue ^^

I'm searching/scanning for the Values in Memory with a tool like CheatEngine (like the current Battery Voltage for example). Then some iterations of changing the current Value (through Cockpit-Interactions) and rescanning the found locations. In the end I have the (current!) Memory-Location where a Value is stored. I then need to find some kind of Pattern in that Memory-Region which always stays the same (like a string). That is also the Reason why finding the Information for "is dashed" on the FCU Displays is so difficult - finding the right bit in Gigabytes of Memory is near to impossible ;)
That Pattern is then what the Binary uses to find the Memory-Location of a Value: Find the Pattern and the Pattern-Address plus an Offset gives the current Memory-Location. It then just reads the Memory-Locations and stores the values formatted or directly to FSUIPC Offsets.

The Binary is / was only really needed for some Display-Contents like the FCU most importantly.
Mostly everything else can be read from the Lvars which Fenix provides, like the IR/ADR Korrys for example:
![image](https://user-images.githubusercontent.com/78614902/206521889-33484205-868a-40c0-9408-fe794444df73.png)
(Screenshot from my shared StreamDeck/PilotsDeck Profile)
<br/>
Fenix have documented this since day one in their Knowledge-Base: https://kb.fenixsim.com/example-of-how-to-use-lvars

**Comment by demariners** [comment]
Hey there, no clue how to PM so I did this instead.
